#!/bin/bash

#   /    Context:                     https://ctx.ist
# ,'`./    do you remember?
# `.,'\
#   \    Copyright 2026-present Context contributors.
#                 SPDX-License-Identifier: Apache-2.0

# Block non-PATH ctx invocations
# This enforces the CONSTITUTION.md rule: "ALWAYS use ctx from PATH"
#
# Generated by: ctx init
#
# BLOCKED PATTERNS:
# - ./ctx, ./dist/ctx, ./dist/ctx-*  (relative paths)
# - go run ./cmd/ctx                  (build-and-run)
# - /absolute/path/to/ctx             (hardcoded absolute paths)
#
# ALLOWED:
# - ctx status, ctx agent, etc.       (PATH-based invocation)

# Read hook input from stdin (JSON)
HOOK_INPUT=$(cat)

# Extract the command being run
COMMAND=$(echo "$HOOK_INPUT" | jq -r '.tool_input.command // empty')

# If no command, allow (not a Bash call we care about)
if [ -z "$COMMAND" ]; then
    exit 0
fi

# Check for forbidden patterns
BLOCKED_REASON=""

# Pattern 1: ./ctx or ./dist/ctx at command position (not as a path argument)
# Must appear at start of command or after a command separator (&&, ||, ;, |)
# to avoid false positives like "git -C ./ctx/path status"
# Note: ^ inside (^|...) alternation doesn't anchor in grep -E, so split the check.
if echo "$COMMAND" | grep -qE '^ *(\./ctx( |$)|\./dist/ctx)' || \
   echo "$COMMAND" | grep -qE '(&&|;|\|\||\|) *(\./ctx( |$)|\./dist/ctx)'; then
    BLOCKED_REASON="Use 'ctx' from PATH, not './ctx' or './dist/ctx'. Ask the user to run: make build && sudo make install"
fi

# Pattern 2: go run ./cmd/ctx
if echo "$COMMAND" | grep -qE 'go run \./cmd/ctx'; then
    BLOCKED_REASON="Use 'ctx' from PATH, not 'go run ./cmd/ctx'. Ask the user to run: make build && sudo make install"
fi

# Pattern 3: Absolute paths to ctx binary at command position
# Match things like /home/user/project/ctx or /tmp/ctx but allow /usr/local/bin/ctx
# Must be at command position to avoid false positives like "git -C /home/user/ctx log"
if echo "$COMMAND" | grep -qE '^ *(/home/|/tmp/|/var/)[^ ]*/ctx( |$)' || \
   echo "$COMMAND" | grep -qE '(&&|;|\|\||\|) *(/home/|/tmp/|/var/)[^ ]*/ctx( |$)'; then
    # Exception: allow /tmp/ctx-test for integration tests
    if ! echo "$COMMAND" | grep -qE '/tmp/ctx-test'; then
        BLOCKED_REASON="Use 'ctx' from PATH, not absolute paths. Ask the user to run: make build && sudo make install"
    fi
fi

# If blocked, output JSON that tells Claude Code to reject
if [ -n "$BLOCKED_REASON" ]; then
    cat << EOF
{"decision": "block", "reason": "$BLOCKED_REASON\n\nSee CONSTITUTION.md: ctx Invocation Invariants"}
EOF
    exit 0
fi

# Allow the command
exit 0
