packages:
  - packages/*
  - apps/*

catalog:
  '@base-ui/react': ^1.0.0
  '@biomejs/biome': ^2.3.10
  '@cloudflare/vite-plugin': ^1.19.0
  '@effect-atom/atom': ^0.4.11
  '@effect-atom/atom-react': ^0.4.4
  '@effect/cli': ^0.73.0
  '@effect/experimental': ^0.58.0
  '@effect/language-service': latest
  '@effect/platform': 0.94.0
  '@effect/platform-bun': ^0.87.0
  '@effect/platform-node': 0.104.0
  '@effect/rpc': ^0.73.0
  '@effect/sql': ^0.49.0
  '@effect/sql-drizzle': ^0.48.0
  '@effect/sql-sqlite-do': ^0.27.0
  '@effect/vitest': ^0.27.0
  '@mozilla/readability': ^0.6.0
  '@opentui/core': 0.1.63
  '@opentui/react': 0.1.63
  '@radix-ui/colors': ^3.0.0
  '@swc/plugin-relay': ^12.3.0
  '@types/bun': ^1.3.5
  '@types/dompurify': ^3.2.0
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-relay': ^18.2.1
  '@types/relay-runtime': ^20.1.0
  '@usirin/forge': ^0.2.0
  better-auth: ^1.4.7
  bluebun: ^0.0.34
  dompurify: ^3.3.1
  drizzle-kit: ^0.31.8
  drizzle-orm: 0.45.1
  effect: ^3.19.13
  ghostty-web: ^0.4.0
  graphql: ^16.12.0
  graphql-yoga: ^5.18.0
  hono: ^4.11.1
  jsonc-parser: ^3.3.1
  linkedom: ^0.18.12
  normalize-url: ^8.1.0
  react: 19.2.3
  react-relay: ^20.1.1
  react-router: ^7.11.0
  relay-compiler: ^20.1.1
  relay-runtime: ^20.1.1
  shiki: ^3.21.0
  turbo: ^2.7.0
  typescript: ^5.9.3
  vitest: ^3.2.0
  wrangler: ^4.62.0

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@lydell/node-pty'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msgpackr-extract
  - sharp
  - workerd
