import {Effect} from "effect"
import {drizzle} from "drizzle-orm/durable-sqlite"
import {migrate} from "drizzle-orm/durable-sqlite/migrator"
import type {DurableObjectState} from "@cloudflare/workers-types/experimental"

/**
 * Drizzle migrations bundle type (generated by drizzle-kit)
 */
export interface DrizzleMigrations {
	journal: {
		entries: Array<{idx: number; when: number; tag: string; breakpoints: boolean}>
	}
	migrations: Record<string, string>
}

/**
 * Runs Drizzle migrations within blockConcurrencyWhile.
 *
 * Wraps the migration in blockConcurrencyWhile to ensure:
 * - No requests processed until migrations complete
 * - Safe concurrent access to storage during migration
 *
 * @example
 * ```ts
 * // In DO constructor
 * Effect.runPromise(runMigrations(ctx, migrations))
 * ```
 */
export const runMigrations = (
	ctx: DurableObjectState,
	migrations: DrizzleMigrations,
): Effect.Effect<void> =>
	Effect.promise(() =>
		ctx.blockConcurrencyWhile(async () => {
			const db = drizzle(ctx.storage)
			migrate(db, migrations)
		}),
	)
